### ISSUE TITLE
detect-feature_and_keypoints issue, cv2 function not recognized

### ISSUE THREAD

**Issue by ThomasFaure-30** [avinashk442/Panoramic-Image-Stitching-using-invariant-features#7]
Hello !
I'd like to use your code for your program but i got an error message telling me this :

Traceback (most recent call last):
  File "C:\Users\thfaure\Desktop\Scripts_python\Panorama_avinashk442\stitch.py", line 35, in <module>
    (result, matched_points) = panaroma.image_stitch([images[no_of_images-2], images[no_of_images-1]], match_status=True)
  File "C:\Users\thfaure\Desktop\Scripts_python\Panorama_avinashk442\panorama.py", line 11, in image_stitch
    (KeypointsA, features_of_A) = self.Detect_Feature_And_KeyPoints(imageA)
  File "C:\Users\thfaure\Desktop\Scripts_python\Panorama_avinashk442\panorama.py", line 43, in Detect_Feature_And_KeyPoints
    descriptors = cv2.xfeatures2d.SIFT_create()
AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'

For the record i'm using python 3.9 and cv2 is on 4.5.1 version.
It seems like the xfeatures2d is no longer a part of the opencv library !
I got the same error message for 2 and more numerous set of multiple images.
Any clue ?

**Comment by avinashk442** [comment]
@ThomasFaure-30  you can try to install opencv-contrib-python that that supports SIFT. 
https://stackoverflow.com/questions/37039224/attributeerror-module-object-has-no-attribute-xfeatures2d-python-opencv-2


```
pip3 uninstall opencv-python
pip3 install -U opencv-contrib-python==3.4.2.16
```

**Comment by avinashk442** [comment]
@ThomasFaure-30 is above solved your problem.

**Comment by Avinash793** [comment]
@ThomasFaure-30 We have updated the repo with latest libraries as of 2024. You can now give a shot! Thanks!
